### ISSUE TITLE
 tutorial/04-logic/04-each-blocks 'generic iterables'の良い翻訳

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#108]
#107

**Comment by rysh** [comment]
> 一般的な反復可能なデータ構造

個人的に↑の訳で問題ない気がしますが、
プログラミング初学者がイメージしやすい言葉を使って意訳してみると
「リストのようなループできるデータ構造」
といった言い方もできるかもしれません。

**Comment by tomoam** [comment]
@rysh 
コメントありがとうございます！

> プログラミング初学者がイメージしやすい言葉を使って意訳してみると
> 「リストのようなループできるデータ構造」

初心者向けには良さそうですね！
ただ、「そもそもリストとは」みたいな部分を、強い人からマサカリが投げられたら恐ろしいですね💦

> 個人的に↑の訳で問題ない気がしますが、

ありがとうございます、他の人がどう思うのか気になってこのissueを作成してたので、このコメントを見て安心しました！
closeしたいと思います！
