### ISSUE TITLE
ドキュメントのバージョンを表記する

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#115]
https://github.com/tomoam/svelte-site-jp/wiki/How-to-fork-from-Svelte-site,-and-How-to-follow-Svelte-site

**Comment by myLifeAsaDog** [comment]
> 〇月〇日時点でのSvelte公式サイトを基にしています

とか表示するしかない気がしますね

**Comment by tomoam** [comment]
そうですねー  
tagにきられたものを取り込むようにしようかとも思ったんですが、siteはblogとかチュートリアルを含むので微妙にサイクルが違って遅れてしまうんですよね・・・  
とはいってもSvelte本体は長くても２週間に1回はリリースされてるし早ければ2日程度でリリースされているので、それに合わせるのもまあまあ現実的かもしれません。
悩みますねー。

**Comment by tomoam** [comment]
#258 で改めてわかりましたが、ソースとしてはバージョン管理されていてもデプロイされるタイミングはそれと関係ないですね。困った。

**Comment by tomoam** [comment]
今のところ、公式自体も大体月に1回程度の更新で、こちらもそれに追従すれば問題なさそうです。

月に1回程度更新する旨もCONTRIBUTING.mdに記載したのでcloseします。
