### ISSUE TITLE
tutorial/07-lifecycle/01-onmouunt not (say) in a setTimeoutの良い日本語訳

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#116]
tutorial/07-lifecycle/01-onmouuntの文章の良い日本語訳を募集中です！

> Lifecycle functions must be called while the component is initialising so that the callback is bound to the component instance — not (say) in a setTimeout.

迷ったところを参考までに：
> 1. **setTimeoutで呼んでるわけではなく**、コールバックはコンポーネントインスタンスにバインドされるから
> 
> というような流れになるんでしょうけど、setTimeoutは意識せずに`this`を入れちゃうと色々問題があるのでちゃんとbindするというのがあって、その文脈を考えると
> 
> 2. **setTimeoutがそうであるように**、コールバックはコンポーネントインスタンスにバインドされるから
> 
> とも読めますね・・・  
> とりあえず1にしておいて、あとで改善しましょう。
> あとでIssueを作成しておきます。
> 

_Originally posted by @tomoam in https://github.com/tomoam/svelte-site-jp/issues/37#issuecomment-774422350_

**Comment by knj4484** [comment]
> Lifecycle functions must be called while the component is initialising so that the callback is bound to the component instance — not (say) in a setTimeout.
この文は、

> Lifecycle functions  
> must be called while ... —  
> must not be called (say) in a setTimeout.

というもともとの文があって、それを省略して

> Lifecycle functions  
> must be called while ... —  
> not (say) in a setTimeout.

という構造になっているんだと思います。

分かりやすくもともとの文を翻訳に反映すると、

「ライフサイクル関数は、コールバックがコンポーネントのインスタンスにバインドされるように、コンポーネントの初期化中に呼び出されなければなりません。例えば、`setTimeout` の中で呼び出されてはいけません。」

のような日本語になります。

**Comment by tomoam** [comment]
@knj4484 
とても助かります！なるほど！実際のSvelteの挙動とも整合が取れていて腑に落ちる翻訳です！
頂いた内容で修正しますね！

**Comment by knj4484** [comment]
@tomoam ご確認ありがとうございました。お忙しそうなので、自分からPRを出しておきます。

**Comment by tomoam** [comment]
@knj4484 
なんてありがたい、本当に助かります！
