### ISSUE TITLE
よく出てくる語彙の翻訳を統一するためのGlossaryやガイドラインを作成する

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#134]
参照：https://discord.com/channels/777141291800723468/806400012136611880/807875345868128256

翻訳が軌道に乗るまでは厳しいルールなどを設けず、表記揺れなどはあとでまとめて修正すれば良いと考えていましたが、結果としてそれがコントリビュートしてくださる方々を迷わせているようです。  
Discordでロシア語化プロジェクトではそういったルールや辞書などを用意しているとアドバイス頂き、日本語化プロジェクトでもそれを用意しようと思います。

参考：  
- ロシア語化プロジェクト
  - https://github.com/AlexxNB/svelte3-translation-ru#%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D0%BE-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%D1%83
  - https://github.com/AlexxNB/svelte3-translation-ru/blob/master/DICTIONARY.md
- React
  - https://github.com/reactjs/ja.reactjs.org
- Vue
  - https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md
- Angular
  - https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md#%E7%BF%BB%E8%A8%B3%E3%81%AE%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3

**Comment by myLifeAsaDog** [comment]
handler - ハンドラ
listen - リッスン
container - コンテナ
development - デベロップメント、もしくは開発

個人的には prop/props をカタカナ表記するのか英語のままにするのかは統一したい感じがしています、
Vuejs だと基本的に英語の方で統一されてるみたいなので。

**Comment by tomoam** [comment]
そうですね、私もprops/propは英語でいいと思います。
今日の夜、ある程度APIの翻訳タスク用issueを作成したらこの辺の辞書を作りますね！

**Comment by tomoam** [comment]
とりあえず[DICTIONARY.md](https://github.com/svelte-jp/svelte-site-jp/blob/master/DICTIONARY.md)を作りました。
内容の追記/変更はどんどんやっちゃってください！

また、現在は表形式にしていますが[Reactのドキュメント](https://github.com/reactjs/ja.reactjs.org/wiki/%E8%A8%B3%E8%AA%9E%E3%81%AE%E7%B5%B1%E4%B8%80)のように箇条書きにしたい場合は変更していただいて大丈夫です！

**Comment by tomoam** [comment]
ガイドラインはある程度 CONTRIBUTING.md に記載していますし、辞書は #260 で継続的に進めていけると思うので、このIssueはCloseします！
