### ISSUE TITLE
tutorial/09-motion/01-tweened tweenの良い日本語訳

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#159]
https://github.com/tomoam/svelte-site-jp/pull/158#pullrequestreview-586156639 から派生

**Comment by ampcpmgp** [comment]
フレーム補完や中割りという言葉が当てはまりそうです。
https://ejje.weblio.jp/content/tweening

tween, tweening をそのまま使うのも有りな気がします。


あと、リンク元が 404 になってますね。 

日本語版: https://github.com/svelte-jp/svelte-site-jp/blob/master/content/tutorial/09-motion/01-tweened/text.ja.md
英語版: https://github.com/svelte-jp/svelte-site-jp/blob/master/content/tutorial/09-motion/01-tweened/text.md

**Comment by tomoam** [comment]
adobeのサイト見てたら普通に「トゥイーン」とあったので、「トゥイーン」で良いかなと思いました。

@ampcpmgp 
教えて頂きありがとうございました！
