### ISSUE TITLE
[API]01-component-format - <script> - '3. $: marks a statement as reactive' を翻訳する

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#184]
https://github.com/svelte-jp/svelte-site-jp/blob/master/content/docs/ja/01-component-format.ja.md#3--marks-a-statement-as-reactive

110~171行目

**Comment by jay-es** [comment]
こちらのパートを翻訳希望ですが、もう募集開始していますか？

**Comment by tomoam** [comment]
まだ正式には募集していませんが、やっていただいて大丈夫です！
あとでアサインいたします！

ただし今回はちゃんと辞書を作成しようと思っているので、PRをいただいた後にそれに合わせていただくよう修正をおねがいするかもしれません💦
こちらの準備が遅れていてすみません。

**Comment by jay-es** [comment]
ありがとうございます:bow:
修正の件も了解いたしました
