### ISSUE TITLE
[API]02-template-syntax - 'Component directives'を翻訳する

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#224]
## 翻訳対象

https://github.com/svelte-jp/svelte-site-jp/blob/master/content/docs/ja/02-template-syntax.ja.md#component-directives

1215~1275行目

## 翻訳方法

[CONTRIBUTING.md](https://github.com/svelte-jp/svelte-site-jp/blob/master/CONTRIBUTING.md)をご参照ください。
また、辞書として[DICTIONARY.md](https://github.com/svelte-jp/svelte-site-jp/blob/master/DICTIONARY.md)もご参照ください。

まだ翻訳プロジェクトが発足してから日が浅いため、ルールや方針は全てのケースを網羅できておりません。  
ご不明な点があればお気軽にお知らせください。

**Comment by kkeeth** [comment]
こちら翻訳お手伝いしますー(=ﾟωﾟ)ﾉ

**Comment by myLifeAsaDog** [comment]
こちらもお願いします！

**Comment by tomoam** [comment]
@kkeeth 
もしお忙しかったりこのIssueが負担になっているようであれば遠慮なくおっしゃってくださいね！
（急かしているわけではありませんので、負担などになっていなければお時間のあるときにご対応いただければ大丈夫です！）

**Comment by kkeeth** [comment]
お気遣いありがとうございますー！
本業落ち着いたので、本日着手します！
