### ISSUE TITLE
[API]02-template-syntax - '<svelte:component>'を翻訳する

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#230]
## 翻訳対象

https://github.com/svelte-jp/svelte-site-jp/blob/master/content/docs/ja/02-template-syntax.ja.md#sveltecomponent

1426~1442行目

## 翻訳方法

[CONTRIBUTING.md](https://github.com/svelte-jp/svelte-site-jp/blob/master/CONTRIBUTING.md)をご参照ください。
また、辞書として[DICTIONARY.md](https://github.com/svelte-jp/svelte-site-jp/blob/master/DICTIONARY.md)もご参照ください。

まだ翻訳プロジェクトが発足してから日が浅いため、ルールや方針は全てのケースを網羅できておりません。  
ご不明な点があればお気軽にお知らせください。

**Comment by ampcpmgp** [comment]
これやります！

**Comment by tomoam** [comment]
ありがとうございます！お願いします！
なにかご不明な点や迷うところがあれば、こちらのIssueでもDiscordでも構いませんのでお気軽にお知らせください！
