### ISSUE TITLE
[API]03-run-time - 'Client-side component API'を翻訳する

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#251]
## 翻訳対象

https://github.com/svelte-jp/svelte-site-jp/blob/master/content/docs/ja/03-run-time.ja.md#client-side-component-api

877~994行目

## 翻訳方法

[CONTRIBUTING.md](https://github.com/svelte-jp/svelte-site-jp/blob/master/CONTRIBUTING.md)をご参照ください。
また、辞書として[DICTIONARY.md](https://github.com/svelte-jp/svelte-site-jp/blob/master/DICTIONARY.md)もご参照ください。

まだ翻訳プロジェクトが発足してから日が浅いため、ルールや方針は全てのケースを網羅できておりません。  
ご不明な点があればお気軽にお知らせください。

**Comment by jay-es** [comment]
こちらやります！

**Comment by tomoam** [comment]
いえ、１つで大丈夫です！
量が多くて大変ですが、よろしくお願いします！
