### ISSUE TITLE
README.mdに貢献者の一覧表示を作成する

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#256]
この日本語翻訳プロジェクトに貢献してくださった方々を表示する部分をREADME.mdに作成したいです。

このプロジェクトはsveltejs/svelteからコミットログを引き継いでいるので、[contributors](https://github.com/svelte-jp/svelte-site-jp/graphs/contributors)に載っている方全て表示すると大変なことになってしまいます。

日本語翻訳に貢献してくださった方のみを載せるのに良いアイデアがあれば教えてください。
まだ人数が少ないので手で書いてもいいかもしれません。

参考：
- https://github.com/all-contributors/all-contributors

**Comment by ampcpmgp** [comment]
TypeScript Deep Dive の日本語訳レポジトリは、 all-contributors-cli を使って、手作業で add してるっぽいですね。
https://github.com/yohamta/typescript-book-jp
https://github.com/yohamta/typescript-book-jp/blame/master/README.md

**Comment by tomoam** [comment]
@ampcpmgp ナイスな情報をありがとうございます！試してみます！

**Comment by tomoam** [comment]
all-contributors-cli 使って入れてみました！
https://github.com/svelte-jp/svelte-site-jp#contributors-

**Comment by tomoam** [comment]
README.mdに記載されているもののうち、翻訳するには直接関係のない
- REPL GitHub integration
- Linking @sveltejs/site-kit and @sveltejs/site-repl
- Translating the API docs

は削除してしまって、Contributorsがもうちょっと上に表示されるようにしたいですね。
あと、直接翻訳文書のPRを出していなくても、情報を提供してくれたりSvelte公式とやり取りしてくれる方も載せられるようにしていきたいと思います。

**Comment by ampcpmgp** [comment]
良い感じですね！

**Comment by tomoam** [comment]
とりあえず対応できているのでcloseします！
