### ISSUE TITLE
[Tutorial]05-events/04-component-events sveltejs本体の変更内容を翻訳する

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#258]
sveltejs/svelteからv3.32.3時点のソースをMerge(#257)。

そこには下記チュートリアルの変更が入っているため、日本語翻訳もこれに合わせて修正する。

- 変更箇所
https://github.com/svelte-jp/svelte-site-jp/tree/master/content/tutorial/05-events/04-component-events

**Comment by myLifeAsaDog** [comment]
これ本体の方にもまだ反映されていないっぽいんですけど、やっておきます

**Comment by tomoam** [comment]
ホントですね。`svelte.dev` は人が手動でmake叩いてGCPにデプロイしているっぽいので、リリースタイミングは完全に人依存なんですよねー。
