### ISSUE TITLE
[Blog]Svelte 3: Rethinking reactivity を翻訳する

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#331]
このポストはトップページの「Truely reactive」や「もっと詳しく知りたい方はこちらの紹介ブログ記事をご覧ください。」(Read the introductory blog post to learn more.) からリンクされています。

## 翻訳対象

https://github.com/svelte-jp/svelte-site-jp/blob/master/content/blog/2019-04-22-svelte-3-rethinking-reactivity.md

実際のURLはこちら
https://svelte-jp.herokuapp.com/blog/svelte-3-rethinking-reactivity

余談ですが、このブログポストに記載されているyoutubeはRich Harris氏の講演の動画で、`React is not reactive` とか、Reactよりパフォーマンスが良いことを示すデモを実演したり、なかなか見応えがあります！

**Comment by myLifeAsaDog** [comment]
これやります
