### ISSUE TITLE
[Blog]The easiest way to get started with Svelte を翻訳する

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#333]
このポストはトップページの「もっと詳しく知りたい方はこちらのquickstart guideをご覧ください。」(See the quickstart guide for more information.) からリンクされています。

## 翻訳対象

https://github.com/svelte-jp/svelte-site-jp/blob/master/content/blog/2017-08-07-the-easiest-way-to-get-started.md

実際のURLはこちら
https://svelte-jp.herokuapp.com/blog/the-easiest-way-to-get-started

**Comment by kkeeth** [comment]
こちら翻訳お手伝いしますー(=ﾟωﾟ)ﾉ

**Comment by myLifeAsaDog** [comment]
お願いします！
