### ISSUE TITLE
和訳での英語のダッシュ「—」の混在

### ISSUE THREAD

**Issue by knj4484** [svelte-jp/svelte-site-jp#381]
Svelteのドキュメントではダッシュ記号（—）が多く使われていますが、和訳に以下のような影響が出ているように感じています。

- 日本語にはない書き方なので、原文を読んだ人にはその存在の意味が分かるが、和訳を求めている（原文を読まない）読者には違和感がありそう
  https://github.com/svelte-jp/svelte-site-jp/blob/bf447b221a6811278c540deb2eb8510ecafd62b5/content/tutorial/06-bindings/10-media-elements/text.ja.md#L27
- おそらくエディタがダッシュをうまく扱えないせいで、ダッシュが2つのハイフンに変換される（場合がある）
  https://github.com/svelte-jp/svelte-site-jp/blob/bf447b221a6811278c540deb2eb8510ecafd62b5/content/tutorial/14-composition/05-slot-props/text.ja.md#L31
- 日本語と英語は根本的に構造が違うので、ダッシュを残そうとすると訳すのが難しい。出来ても和訳の構造が不自然になり、意味が分かりにくくなる場合がある
  https://github.com/svelte-jp/svelte-site-jp/blob/bf447b221a6811278c540deb2eb8510ecafd62b5/content/tutorial/04-logic/04-each-blocks/text.ja.md#L29
  - おそらくこの理由でダッシュを既に消している和訳もある

ダッシュを日本語に混在させることについて、皆様のご意見はいかがでしょうか？

個人的には、ダッシュを残すよりも、日本語らしい記号の使い方や文構造にする方が良いかなと考えています。
ただし、箇条書きの項目と説明を区切るダッシュは翻訳のしにくさや読みやすさと関係ないので原文のままでいいかもしれません（コロン「:」を使うのが見慣れた記法ではありますが）。
https://github.com/svelte-jp/svelte-site-jp/blob/bf447b221a6811278c540deb2eb8510ecafd62b5/content/tutorial/09-motion/01-tweened/text.ja.md#L35

作業としては`content/tutorial/**/*.ja.md`を対象にして`^[^*-].* (--|—)`を検索して修正すれば良いので比較的簡単かなと思います（現状で14件）。

**Comment by tomoam** [comment]
とても良いご意見をありがとうございます。
実はこれもどうしようか迷っているところの１つでした。

原文でダッシュが使われているケースの多くは直前の文書の補足をしていて、文と文に挟まれている場合は`()`にする、ダッシュ以降がその段落の最後の文章だったらダッシュを消す、というルールでいけるのではないかと考えていました。

ちなみに、`:`は原文でコードブロックを提示する直前に使われることが多いので、`:`に置き換えるのは望ましくないと考えています。
