### ISSUE TITLE
PRのマージ方法

### ISSUE THREAD

**Issue by knj4484** [svelte-jp/svelte-site-jp#394]
本家Svelteのリポジトリは、masterブランチの履歴が一直線で分かりやすくなるように、PRをマージする際にSquash and Mergeしていると思います。

c.f. [GitHubのMerge、Squash and Merge、Rebase and Mergeを理解する | NHN Cloud Meetup](https://meetup-jp.toast.com/439)

こちらのリポジトリも、Squash and Merge（取り込むブランチの状況によってはRebase and Mergeも可）にしませんか？

**Comment by tomoam** [comment]
とても良いご提案ありがとうございます！

PRを取り込むのにMergeコミットを作成していたことについて、特に理由はありません。
なんとなく惰性でそうしてしまっていました。
実は何回か切り替えようとしたことがあって、いくつかのPRはRebaseで取り込んだりしていますが、統一感がなくなるのではと思いMergeコミットを作る運用に戻してしまっていました。

これからはSquashもしくはRebaseで取り込む運用に変えたいと思います！

@myLifeAsaDog 
何か気になる点などございますか？

**Comment by knj4484** [comment]
ありがとうございます。

他の方が書いてくださった和訳を修正するときに「レビューで何か言われてこうなっているのかな」と疑問に思うことがよくあって、Squash and MergeによってコミットタイトルからPRにリンクされるようになるととても助かります。あと、masterに自分のブランチ名が入らなくなるので、ブランチを作るときに悩まなくて済むようになります。

もしrebaseする必要が出てきたら、取り込むブランチのコミットタイトルも本家に取り込まれることを踏まえたレビュー（日本語やスペルミスがないかetc.）をするように気をつけた方がいいのかもしれないですね。

**Comment by myLifeAsaDog** [comment]
github の allow squash merging を有効にする感じですかね？
特に気にしたことはないので、どちらでもいいと個人的には思っています。

**Comment by tomoam** [comment]
ここ最近のPRをSquashで実施していますがこれで良さそうですね！

@knj4484 
問題なければcloseしちゃってください、ご提案ありがとうございました！

**Comment by knj4484** [comment]
ありがとうございます。
git logが見やすくなり、PRの参照も簡単になりました。
