### ISSUE TITLE
【提案】 npm run lint の改修

### ISSUE THREAD

**Issue by myLifeAsaDog** [svelte-jp/svelte-site-jp#419]
現状、`npm run lint` で `jtf-style` のチェックができるようになっていますが、下記の2点を修正したいです。

1. `CONTRIBUTING.md` でエラーが出るが、そもそも翻訳文ではないので対象から外したい
2. tutorial ディレクトリ以下しかチェックしていないので、チェック対象を `./content/**/**/*.ja.md` にしたい
3. 上記でカバーできないディレクトリは、個別に追加する

ごめん、3点だった

**Comment by knj4484** [comment]
> 1. `CONTRIBUTING.md` でエラーが出るが、そもそも翻訳文ではないので対象から外したい

エラー出ちゃってますね。ごめんなさい。直しておきます。
ただ、「ガイドラインを守ってください」とお願いするファイル自体がガイドラインを守ることは大事だと思うので、翻訳文ではなくてもlintの対象にしてあっていいのではないかと個人的には考えています。

> 2. tutorial ディレクトリ以下しかチェックしていないので、チェック対象を `./content/**/**/*.ja.md` にしたい

マイルストーンに「チュートリアルのフォーマット云々」というのがあったのでtutorial ディレクトリ以下を対象にしていたのですが、最近は./content以下も結構いじっているので良いことだと思います。

> 3. 上記でカバーできないディレクトリは、個別に追加する

いいと思います。

**Comment by myLifeAsaDog** [comment]
下記の列で「閉じ括弧の前に句点を打ってはならない」というルールに違反しているためにエラーが出ているのですが、

`和訳で文と文の区切りになっている場合、ダッシュの代わりに句点「。」を打ってください`

Unicode エスケープシーケンスとかにしちゃえばいいのかなあ
