### ISSUE TITLE
prop/propsの訳し方

### ISSUE THREAD

**Issue by knj4484** [svelte-jp/svelte-site-jp#431]
https://github.com/svelte-jp/svelte-site-jp/blob/master/DICTIONARY.md
> prop/props | prop/props | 英語のままで統一する。「プロップ」「プロップス」としない。

という方針になっていますが、原文の文章中の'prop'や'props'はどちらも和訳では「プロパティ」と書くことにしませんか？

以下の説明にあるように、英語の表記としては短縮されるということですが、表している概念や本来の用語としてはプロパティなので、和訳では「プロパティ」にするのが自然で読みやすいかなと考えています。
[Props / Declaring props • Svelte Tutorial](https://svelte.dev/tutorial/declaring-props)
> we need to declare properties, generally shortened to 'props'. 

appやappsを「アプリ」「アプリケーション」というカタカナ語にするのに似た感覚です。

また、和訳の中でpropとpropsを使うのは以下のような問題があるように感じます。

- 原文で単複を区別する英文法に従って'prop'と'props'が書き分けられているが、単複の区別がない日本語にそのままの表記を持ち込むと違和感がある
- 他の語は、コード上に現れるキーワードや識別子を表している場合は英語そのまま、概念を表している場合はカタカナ語にするという基本方針に反していて混乱がある

**Comment by tomoam** [comment]
Vueのドキュメントでは prop/props はそのままになっていると思っていたのですが、どうやら勘違いでした。

- 英語
  - https://vuejs.org/v2/guide/components-props.html#One-Way-Data-Flow
    > All props form a one-way-down binding...
- 日本語
  - https://jp.vuejs.org/v2/guide/components-props.html#%E5%8D%98%E6%96%B9%E5%90%91%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%83%95%E3%83%AD%E3%83%BC
    > 全てのプロパティは、子プロパティと...

コードとして `props` と書くところだけそのままにしていたんですね。
- https://jp.vuejs.org/v2/api/#props

そうであればSvelteでも「プロパティ」にしてしまいましょう！

@myLifeAsaDog 
どうでしょう？

**Comment by myLifeAsaDog** [comment]
問題ないと思います
