### ISSUE TITLE
ドメインの変更(sveltejp.dev -> svelte.jp)

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#441]
2021/6/10現在、Svelteの日本語翻訳サイトは sveltejp.dev ドメインを使用しています。
sveltejp.dev はドメインをホスティングサービス(現在はheroku)やCDN(現在はcloudflare)でサンプルとして使用するために私が取得したもので、下記のデメリットがあります。

- `svelte`というキーワードで検索したときにドメインでは引っかからない
- 偽物のように見える
  ※日本語翻訳サイトは[Discordを通じて](https://discord.com/channels/457912077277855764/750401468569354431/807285357841875004)日本語翻訳を行う旨をSvelte公式に報告し、お祝いのリアクションを頂いています！

そのため、ロシア語サイト ru.svelte.dev のように日本語のサブドメインを割り当ててもらえないか[依頼をしましたが](https://github.com/sveltejs/svelte/issues/6038)、今のところ返信はありません。
現在SvelteチームはSvelteKitの開発に注力していて、個人的にはその邪魔はしたくありません。また、見ず知らずの人間がホストしたサイトにサブドメインを割り付ける、というのも抵抗があると思います。なのでしつこく催促するようなことはしたくありません。

他の言語のサイトを見てみると、例えば韓国や中国の翻訳サイトでは [svelteに関する文言].[トップレベルドメイン]でホストしているようです。

- 韓国語翻訳サイト
  - http://www.svelte.kr/
- 中国語翻訳サイト
  - https://www.sveltejs.cn

日本語翻訳サイトも、svelte.jp などでホストできると良いと思います。

### ロシア語サイト

- リポジトリ
  - https://github.com/AlexxNB/svelte3-translation-ru
- URL
  - ru.svelte.dev
 
ロシア語のサイトはAlexxNBさんが中心となって構築されていて、ロシア語サイト用のサブドメイン `ru.svelte.dev` が割り当てられています。DiscordでAlexxNBさんご本人が解説されている情報によると、固定IPでホストし、そのIPに対して `ru.svelte.dev` を割り当てるDNSレコードを登録してもらっているようです。

なお、Discord上でその割り当てを依頼しているようなやり取りは見当たらないので、直接Rich Harrisさんに依頼されているものと推測しています。

**Comment by tomoam** [comment]
追記：

svelte.jp のドメインをdynamisさんが所有してるようでしたのでお声掛けしたところ、日本のコミュニティ向けのために確保してくれていたとのこと！
https://twitter.com/dynamitter/status/1380534422869438468

**Comment by dynamis** [comment]
この手のドメインは企業や全く関係のない組織が確保してコミュニティが困ると言うことが多々あり (お仕事絡みでそういう問題に直面した経験もあり)、Svelte については応援したいフレームワークと思っていたので (コミュニティ立ち上げを自分で出来るのが理想だったのですが) ひとまずドメインは確保しておいたというものです。

ちゃんとアクティブに公式ドキュメントを翻訳されているコミュニティに使って頂くために継続課金しているやつなので、本コミュニティにて  sveltejp.dev を svlete.jp に移転させたいとか何か別のドキュメントなりサービスなりで使い分けたいとかあるようでしたらご協力します。

設定すべき DNS 設定など指示いただければいつでも対応します＆ドメインの費用は私のカンパで今後も自動継続課金しておけます。

**Comment by tomoam** [comment]
ありがとうございます！

ドメインは`sveltejp.dev` から `svelte.jp` に、`kit.sveltejp.dev` から `kit.svelte.jp` に移行したいと考えております。
おそらく`CNAME` レコードの設定を依頼させて頂くことになるかと思いますが、
現在どのような構成になっているか情報をまとめてご説明させて頂いてからのほうが良いかと思っております。

情報をまとめ次第、あらためてメンションさせていただきます。
（今週末中にまとめますので、おそらく週明けになるかと思います）

**Comment by tomoam** [comment]
## 現在の日本語ドキュメント環境について

現在はheroku(svelte-jp.herokuapp.com)でホストして、Cloudflare経由(sveltejp.dev)でアクセスさせるようにしています。
![image](https://user-images.githubusercontent.com/29677552/121828625-1a98a100-ccfb-11eb-845e-f58abe164d37.png)

herokuを使用している理由は、SvelteのsiteのREPLを動作させるためにはNode Serverが必要で、コンテナをホストできる環境が必要だからです(公式(svelte.dev)はGoogle Cloud Run + Cloudflareのようです)。

Cloudflareを使用している理由は、herokuでは無料プランだとカスタムドメインでSSLにできないためです。


## 今後の動向について

svelte.devはSvelteKitで作り直される見込みで、SvelteKitはServerless functionに対応していく流れなので、今後はこちらもHerokuに縛られることがなくなると予想されます。

一方で、SvelteのコアメンテナーにCloudflareの方がいらっしゃることもあり、svelte.devもkit.svelte.devもCloudflareを経由する方式から離れることはないかと思います。こちらもそれに合わせて、Cloudflareを経由する方式を続けていきたいと考えています。


## 今後の流れとご依頼事項

Svelte日本語翻訳サイトで使用している

1. svelte.jpの

**Comment by tomoam** [comment]
@dynamis 

## 現在の日本語ドキュメント環境について

現在はheroku(svelte-jp.herokuapp.com)でホストして、Cloudflare経由(sveltejp.dev)でアクセスさせるようにしています。
![image](https://user-images.githubusercontent.com/29677552/121828625-1a98a100-ccfb-11eb-845e-f58abe164d37.png)

herokuを使用している理由は、SvelteのsiteのREPLを動作させるためにはNode Serverが必要で、コンテナをホストできる環境が必要だからです(公式(svelte.dev)はGoogle Cloud Run + Cloudflareのようです)。

Cloudflareを使用している理由は、herokuでは無料プランだとカスタムドメインでSSLにできないためです。


## 今後の動向について

svelte.devはSvelteKitで作り直される見込みで、SvelteKitはServerless functionに対応していく流れなので、今後はこちらもHerokuに縛られることがなくなると予想されます。

一方で、SvelteのコアメンテナーにCloudflareの方がいらっしゃることもあり、svelte.devもkit.svelte.devもCloudflareを経由する方式から離れることはないかと思います。こちらもそれに合わせて、Cloudflareを経由する方式を続けていきたいと考えています。


## 今後の流れ

DNSの設定依頼については、セキュリティを気にして念の為DMでご依頼させて頂きます。

**Comment by dynamis** [comment]
DM にお返事したとおり Cloudflare の NS を指定する形に設定変更を行いました。
反映に暫く時間が掛かるかも知れませんが、反映され次第各種設定を行ってくださいませ。

**Comment by tomoam** [comment]
@dynamis 

ご対応ありがとうございました。
おかげさまで移行することができました、本当に嬉しいです！

Contributorsにもdynamisさんを追加させて頂きました。
※ドメインの保護と提供に適したアイコンがなかったのでfinancialとinfraにしていますが、別のものがよければ仰ってください
https://github.com/svelte-jp/svelte-site-jp#contributors-

> ドメインの費用は私のカンパで今後も自動継続課金しておけます。

こちらの件ありがとうございます。
ただ、もし金銭的に負担になっている場合は私のほうでお支払いすることも可能ですので仰ってください。
ドメインの移譲でも大丈夫ですし、私がdynamisさんのGitHubスポンサーになるとかでも大丈夫です！

その他、ご不明点やご質問などあればお気軽にお知らせください。
これまでドメインを保護してきてくれたこと、使用させてくれること、コミュニティに加わってくださったことに深く感謝します！

**Comment by tomoam** [comment]
sveltejp.dev から svelte.jp への転送も上手くいっているようなので、closeします！
