### ISSUE TITLE
[Blog]Sapper: Towards the ideal web app frameworkの翻訳

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#444]
## 対象ドキュメント

- 対象ファイル
  - [Sapper: Towards the ideal web app framework](https://github.com/svelte-jp/svelte-site-jp/blob/master/content/blog/ja/2017-12-31-sapper-towards-the-ideal-web-app-framework.ja.md)
- URL
  - https://sveltejp.dev/blog/sapper-towards-the-ideal-web-app-framework

## 翻訳したい/してほしい

- 翻訳してほしい

## 備考

もう既に後継のSveltKitが公開されていますが、フレームワークに求められるもの、思想などがぎっしり詰まっている良い記事です。

**Comment by lunain84** [comment]
記事が長いので少し時間がかかりそうですが、翻訳させていただいてもよろしいでしょうか！

**Comment by myLifeAsaDog** [comment]
@lunain84 よろしくおねがいします、途中までで無理そうだったら、そこまででも大丈夫なので教えてください！

**Comment by lunain84** [comment]
こちらclose していただいて大丈夫そうです！
