### ISSUE TITLE
OGPのURLを変更する

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#451]
URLは svelte.jp ですがOGPは svelte.dev なのは良くない気がします。
![image](https://user-images.githubusercontent.com/29677552/122311131-7c9c1500-cf4c-11eb-835f-a43a7f8235f1.png)

svelte.dev から svelte.jp に修正したいです。

**Comment by myLifeAsaDog** [comment]
確かに

**Comment by tomoam** [comment]
試しに作ってみました。
![twitter-card_jp](https://user-images.githubusercontent.com/29677552/122396063-953f1600-cfb2-11eb-8769-9770b409695f.png)

**Comment by tomoam** [comment]
新しいサイトではURLが入らないので解決です
![image](https://user-images.githubusercontent.com/29677552/148332642-0ef0e82a-6cfe-4008-97a3-2788dfdff126.png)
