### ISSUE TITLE
CONTRIBUTING.mdのリンク修正要望

### ISSUE THREAD

**Issue by Murayu0225** [svelte-jp/svelte-site-jp#456]
## 対象ドキュメント
- [CONTRIBUTING.md](https://github.com/svelte-jp/svelte-site-jp/blob/master/CONTRIBUTING.md)

## 対象箇所
`貢献するには`の日本語ドキュメントサイトと書かれた部分のリンクが正しくないと思います。

- 現在
  - 日本語ドキュメントサイト(https://svelte.jp/)を使ってみてください。気になるところや改善点があれば[Issueを開いて](#issueを作成する)お知らせください。

- 修正案
  - 日本語ドキュメントサイト([https://svelte.jp/](https://svelte.jp/))を使ってみてください。気になるところや改善点があれば[Issueを開いて](#issueを作成する)お知らせください。

## 修正したい/してほしい

- 修正したい

## 備考
簡単な内容ですみません。どういうものなのかと思い`CONTRIBUTING.md`を読んでいたところ見つけたので早速Issueを書きました。よろしくお願いします🙇

**Comment by myLifeAsaDog** [comment]
@Murayu0225 ご指摘ありがとうございます！

「修正したい」ということは PR を作ってもらえるという理解でいいでしょうか？
作成したPRには当ISSUEの番号を `close #456` みたいな感じで書いておいてもらえると助かります！

**Comment by Murayu0225** [comment]
@myLifeAsaDog 
先ほどの案でよろしければ、私がPRも作ります。
PRへのIssue番号の記載、了解しました。

**Comment by Murayu0225** [comment]
#457 を作成しました。
