### ISSUE TITLE
[Blog]What's new in Svelte: July 2021 の翻訳

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#461]
## 対象ドキュメント

- 対象ファイル
  - https://github.com/svelte-jp/svelte-site-jp/blob/master/content/blog/ja/2021-07-01-whats-new-in-svelte-july-2021.ja.md

## 翻訳したい/してほしい

- 翻訳したい

## 備考

特になし

**Comment by ampcpmgp** [comment]
この記事気になってたんでやります

**Comment by tomoam** [comment]
@ampcpmgp 
まだ着手していないのでお願いできますか？

**Comment by ampcpmgp** [comment]
@tomoam OKです！
