### ISSUE TITLE
[Docs]01-component-format 更新/追加部分の翻訳

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#462]
## 対象ドキュメント

- 対象ファイル
  - [content/docs/ja/01-component-format.ja.md の変更部分](https://github.com/svelte-jp/svelte-site-jp/pull/460/files#diff-c0b116cdd2f01a9e29d94fb3adb769349a714081be53da54d08ac4babad2c847)
    - 60-61行目
    - 282-290行目
    - 305-324行目

## 翻訳したい/してほしい

- 翻訳してほしい

## 備考

特になし

**Comment by jay-es** [comment]
こちら対応します

**Comment by tomoam** [comment]
ありがとうございます、お願いします！
