### ISSUE TITLE
[Docs]04-compile-time varsReport の翻訳

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#465]
## 対象ドキュメント

- 対象ファイル
  - [content/docs/ja/04-compile-time.ja.md の追加部分](https://github.com/svelte-jp/svelte-site-jp/pull/460/files#diff-e3093898533feb897c17352992e386e61d5c7c18fd7a53376e1562aff1ee4f05)
    - ※翻訳は70行目のみ

## 翻訳したい/してほしい

- 翻訳してほしい

## 備考

特になし

**Comment by myLifeAsaDog** [comment]
これ自分がやっておきます

**Comment by tomoam** [comment]
ありがとうございます、お願いします！
