### ISSUE TITLE
[Tutorial]07-lifecycle/02-ondestroy 追加部分の翻訳

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#468]
## 対象ドキュメント

- 対象ファイル
  - [content/tutorial/07-lifecycle/02-ondestroy/text.ja.md の追加部分](https://github.com/svelte-jp/svelte-site-jp/pull/460/files#diff-f9fc9633dbcdf0e07ac5c522a575e3cc2a625062bc042568f29bb28312ce2b3b)
    - 45行目のみ

## 翻訳したい/してほしい

- 翻訳してほしい

## 備考

特になし

**Comment by lunain84** [comment]
初めまして．OSS初心者ですが，この翻訳をやらせていただいてもよろしいでしょうか？

**Comment by myLifeAsaDog** [comment]
@lunain84 もちろんです、よろしくお願いします！
