### ISSUE TITLE
[Blog]What's new in Svelte: August 2021 の翻訳

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#482]
## 対象ドキュメント

- 対象ファイル
  - https://github.com/svelte-jp/svelte-site-jp/blob/master/content/blog/ja/2021-08-01-whats-new-in-svelte-august-2021.ja.md

## 翻訳したい/してほしい

- 翻訳してほしい

## 備考

特にありません。
ご質問などありましたらお気軽にコメントください！

**Comment by yamanoku** [comment]
@tomoam 
https://github.com/svelte-jp/svelte-site-jp/issues/483 で手を上げてたのですが間違って8月の翻訳をやっちゃってました（エヘヘ）
プルリクエストも出すのでこちらも担当させてください🙇🏼

**Comment by tomoam** [comment]
@yamanoku 
承知しました、ありがとうございます！
