### ISSUE TITLE
[Blog]What's new in Svelte: September 2021 の翻訳

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#483]
## 対象ドキュメント

- 対象ファイル
  - https://github.com/svelte-jp/svelte-site-jp/blob/master/content/blog/ja/2021-09-01-whats-new-in-svelte-september-2021.ja.md

## 翻訳したい/してほしい

- 翻訳してほしい

## 備考

特にありません。
ご質問などありましたらお気軽にコメントください！

**Comment by yamanoku** [comment]
@tomoam やります！ニュース初めてですがよろしくおねがいします 🙏🏼

**Comment by tomoam** [comment]
@yamanoku ありがとうございます！お願いします！

**Comment by tomoam** [comment]
yamanokuさんが #482 を担当してくださいましたので、こちらは一旦アサインなどを元に戻しますね！

**Comment by oekazuma** [comment]
@tomoam こちら翻訳対応します！

**Comment by tomoam** [comment]
ありがとうございます！
