### ISSUE TITLE
[Blog]What's new in Svelte: November 2021の翻訳

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#492]
## 対象ドキュメント

- 対象ファイル
  - https://github.com/svelte-jp/svelte-site-jp/blob/master/site/content/blog/2021-11-01-whats-new-in-svelte-november-2021.md

## 翻訳したい/してほしい

- 翻訳してほしい

### コントリビュートしたことがある方へ

11/2 にこのプロジェクトの構成が大きく変わっています。
過去にコントリビュートしたことがある方は、お手数ですがForkし直すか、新たにCloneしてください。

### 初めてコントリビュートする方へ

こちらに翻訳するときの流れなどが記載してありますので、ご一読ください。
[翻訳の流れ - CONTRIBUTING_ja.md](https://github.com/svelte-jp/svelte-site-jp/blob/master/CONTRIBUTING_ja.md#%E7%BF%BB%E8%A8%B3%E3%81%AE%E6%B5%81%E3%82%8C)

わからないことなどがあれば、お気軽にお知らせください！

**Comment by nullnyat** [comment]
この翻訳やりたいです！

**Comment by tomoam** [comment]
@nullnyat 
ありがとうございます、アサインさせて頂きました！
わからないことがあれがお気軽にご質問ください！
