### ISSUE TITLE
Introduction/Dynamic Attributesのgifが表示されない。

### ISSUE THREAD

**Issue by ryoppippi** [svelte-jp/svelte-site-jp#511]
https://svelte.jp/tutorial/dynamic-attributes
gifが表示されていないようです。
英語のページでは問題なく表示されています。
https://svelte.dev/tutorial/dynamic-attributes

このレポジトリのコードを見たのですが、image.gifがどこにあるのか確認できなかったため、Issueを立てさせていただきました。
![スクリーンショット 2021-12-27 9 38 14](https://user-images.githubusercontent.com/1560508/147423767-705666cc-8c4e-4410-8fb9-5d46cb7ca463.png)

**Comment by tomoam** [comment]
お知らせ頂きありがとうございます、とても助かります！

6日前にsveltejs/svelteでも修正が入っていました。この修正を日本語サイトにも取り込みますので、少々お待ちください。

https://github.com/sveltejs/svelte/commit/35376f248753d86ea6b38a0676cdb43d803b9efd#diff-4c1aa00fdb3078d9cd5d53f4847939272d54c65a118d3599fc7a1b664fee71ea

**Comment by tomoam** [comment]
対応しました、ご連絡ありがとうございました！

**Comment by ryoppippi** [comment]
ありがとうございました！
