### ISSUE TITLE
翻訳改善要望

### ISSUE THREAD

**Issue by AFURO-1130** [svelte-jp/svelte-site-jp#560]
## 対象ドキュメント

対象となるファイルパスが見つけられなくて申し訳ないです。(blogディレクトリの配下は2022-12-01のファイルは確認してみました。)

https://svelte.jp/blog/announcing-sveltekit-1.0

![A5B35185-62B5-45F7-B169-A3A947D11446](https://user-images.githubusercontent.com/73173075/207808318-edb1d1cb-a010-4d3d-b1ff-b1e81e1610b2.png)

## 対象箇所

誤り: サンバmサイドレンダリングを追加するには?
正: サーバーサイドレンダリングを追加するには?

## 修正したい/してほしい

- 修正したい

**Comment by tomoam** [comment]
ありがとうございます！
実は、Sveltekit 1.0 リリースに伴い、ブログ記事のマークダウンファイルが [sveltejs/sites](https://github.com/sveltejs/sites) (日本語翻訳版は [svelte-jp/sites](https://github.com/svelte-jp/sites)) に移動されました。

該当のファイルはこちらになります。

https://github.com/svelte-jp/sites/blob/master/sites/svelte.dev/content/blog/2022-12-14-announcing-sveltekit-1.0.md

もし修正して頂けるなら、このファイルを修正し、PRを出して頂けると助かります！
PRを作成する際、sveltejs/sites にPRを作成しないようご注意ください。
(svelte-jp/sites はまだコントリビュート関係のドキュメントをまとめていないので、どこに何があるかわかりにくいかもしれません、すみません。)

**Comment by tomoam** [comment]
大変申し訳ありません、すでに別の方が修正の PR を作成してくださってました。
https://github.com/svelte-jp/sites/pull/19

ご連絡、ご対応しようとしてくださっていたこと、本当にありがとうございます！
また何かありましたら、お知らせ頂けると助かります。

**Comment by AFURO-1130** [comment]
承知しました！わざわざ調べてくださってありがとうございます！また何かありましたら、連絡さしてもらいます！ありがとうございます！！
