### ISSUE TITLE
TypeScriptセクションの翻訳

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#584]
## 対象ドキュメント

- 対象ファイル
  - [docs/05-misc/03-typescript.md](https://github.com/svelte-jp/svelte-site-jp/blob/master/documentation/docs/05-misc/03-typescript.md)

## 翻訳したい/してほしい

- 翻訳してほしい

## 備考

こちらのページです: https://svelte.jp/docs/typescript

**Comment by shuuji3** [comment]
はじめまして🙂 こちらのドキュメントの翻訳をしようと思います。
