### ISSUE TITLE
06-bindings/01-text-inputsのMarkDown誤字

### ISSUE THREAD

**Issue by z4m1** [svelte-jp/svelte-site-jp#610]
## 対象ドキュメント
https://github.com/svelte-jp/svelte-site-jp/blob/svelte-4/documentation/tutorial/06-bindings/01-text-inputs/text.md

## 対象箇所
```
er--
title: Text inputs
---
```

## 修正したい/してほしい

- 修正してほしい

**Comment by tomoam** [comment]
ご報告ありがとうございます、修正しました！
https://svelte.jp/tutorial/text-inputs
