### ISSUE TITLE
ChatをドロップダウンメニューにしてSvelte日本Discordへのリンクを追加する

### ISSUE THREAD

**Issue by tomoam** [svelte-jp/svelte-site-jp#96]
参照：Discord
https://discord.com/channels/777141291800723468/806400012136611880/806638112297189376

**Comment by takoyaro** [comment]
純粋主義者はメニューを変えるべきではないと言うかもしれませんが、この件についてあなたの意見や提案を聞きたいです。

ドロップダウンをするという最初の提案は私からですが、もっと良いアイデアがあるはずです!

**Comment by tomoam** [comment]
ロシアの方のサイトではChatが無効になっているみたいですね。
https://ru.svelte.dev/

日本語化サイトでは、公式のDiscordも、Svelte日本のDiscordも、どちらのリンクも載せたいと思います。
@takoyaro さんが考えてくれた実装方法として、次のものがあります。
- メニューを並べる
- ドロップダウンメニューにする

私はドロップダウンメニューがいいと思いましたが、他に良いアイデアがあれば検討したいと思っています！

**Comment by tomoam** [comment]
ちなみに今この右端にあるドロップダウンは突貫で適当に作ったものなので、もっと良い実装をしてくれる方がいらっしゃると嬉しいです！
![image](https://user-images.githubusercontent.com/29677552/107228849-78249480-6a60-11eb-9a87-4827d42af1b3.png)

**Comment by tomoam** [comment]
突貫のドロップダウンの実装で、Svelte日本Discordへのリンクを追加しました。
とりあえずこれでSvelte日本へ案内することができるようになりました！
![image](https://user-images.githubusercontent.com/29677552/107494398-16843780-6bd2-11eb-9d82-265502b5ff4f.png)

**Comment by tomoam** [comment]
問題なさそうなので、閉じますね！
